version: "3.7"
services:
  app:
    build:
      context: ./
      # select docker base (localhost, development, production) - default localhost
      target: ${NODE_ENV:-localhost}
    environment:
      redisHost: ${redisHost} # default "127.0.0.1"
      redisPort: ${redisPort} # default 6379
      mysqlHost: ${mysqlHost} # default "127.0.0.1"
      mysqlPort: ${mysqlPort} # default 3306
      mysqlUserName: ${mysqlUserName}
      mysqlDataBase: ${mysqlDataBase}
      mysqlPassword: ${mysqlPassword}
      # select app envierment (localhost, development, production) - default localhost
      NODE_ENV: ${NODE_ENV:-localhost}
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dockerStart